server:
  port: 8081

com:
  dxk:
    microservice:
      datasource:
        druid:
          enable: true
          url: mysql://127.0.0.1:3306/scaffold-cloud?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&serverTimeZone=GMT
          username: root
          password: 123456
          #com.mysql.cj.jdbc.Driver
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: mysql
          #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall
          #数据源其他配置
          initialSize: 0
          minIdle: 8
          maxActive: 8
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          useGlobalDataSourceStat: true
          #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          web:
            enable: true
            loginUserName: druid
            loginPassword: druid

mybatis-plus:
  enable: true
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0